spring:
  main:
    banner-mode: "off"
logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG

amazon:
  associateId: yourId
management:
  endpoints:
    web:
      exposure:
        include: "*"